apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: generate-uid-task
spec:
  description: |
    Generate a UID for pipelinerun.
  params:
  results:
    - name: uid
      description: The UID.
  steps:
  - name: generate-uid
    image: python:3
    script: |
      #!/usr/bin/env bash

      uuid=$(python -c 'import uuid; print(uuid.uuid1())')

      echo -n "${uuid}" | tee $(results.uid.path)
