apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: build-canary-deploy-iter8-pipelinerun-0d78da8
spec:
  pipelineRef:
    name: build-canary-deploy-iter8-pipeline
  resources:
    - name: git-source
      resourceRef:
        name: reviews-repo
    - name: docker-image
      resourceRef: 
        name: reviews-image
  params:
    - name: image-tag
      value: 0d78da8
    - name: image-name
      value: index.docker.io/reviews        
    - name: release-name
      value: reviews
    - name: target-namespace
      value: demo
    - name: experiment-id
      value: 0d78da8
