apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: build-canary-deploy-iter8-pipeline
spec:
  resources:
    - name: git-source
      type: git
    - name: docker-image
      type: image
  params:
    - name: image-tag
      default: latest
    - name: image-name
      default: index.docker.io/myservice
    - name: release-name
      default: myservice
    - name: repository-name
      default: myservice
    - name: target-namespace
      default: default
    - name: docker-registry
      default: index.docker.io

    - name: pathToDockerFile
      default: /workspace/git-source/Dockerfile
    - name: pathToContext
      default: /workspace/git-source
    - name: experiment
      default: "iter8/experiment.yaml"
    - name: experiment-id
      default: guid
    - name: stable
      default: stable
    - name: candidate
      default: candidate
  tasks:
    - name: build
      taskRef:
        name: build-task
      resources:
        inputs:
          - name: git-source
            resource: git-source
        outputs:
          - name: docker-image
            resource: docker-image
      params:
        - name: pathToDockerFile
          value: ${params.pathToDockerFile}
        - name: pathToContext
          value: ${params.pathToContext}
    - name: generate-load
      taskRef:
        name: generate-load-task
      runAfter: ["build"]
      resources:
        inputs:
          - name: git-source
            resource: git-source
      params:
        - name: image-tag
          value: "${params.image-tag}"
        - name: target-namespace
          value: "${params.target-namespace}"
    - name: create-experiment
      taskRef:
        name: create-experiment-task
      runAfter: ["build"]
      resources:
        inputs:
          - name: git-source
            resource: git-source
          - name: docker-image
            resource: docker-image
      params:
        - name: image-tag
          value: "${params.image-tag}"
        - name: experiment
          value: "${params.experiment}"
        - name: experiment-id
          value: "${params.image-tag}"
        - name: target-namespace
          value: "${params.target-namespace}"
    - name: deploy
      taskRef:
        name: deploy-task
      runAfter: ["create-experiment"]
      resources:
        inputs:
          - name: git-source
            resource: git-source
          - name: docker-image
            resource: docker-image
      params:
        - name: image-tag
          value: "${params.image-tag}"
        - name: target-namespace
          value: "${params.target-namespace}"
    - name: wait-completion
      taskRef:
        name: wait-completion-task
      runAfter: [ "create-experiment" ]
      resources:
        inputs:
          - name: git-source
            resource: git-source
      params:
        - name: experiment-template
          value: "${params.experiment}"
        - name: experiment-id
          value: "${params.image-tag}"
        - name: target-namespace
          value: "${params.target-namespace}"
