kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: experiment-stop-claim-bookinfo-iter8
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Ki
