apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build-task
spec:
  inputs:
    resources:
      - name: git-source
        type: git
    params:
      - name: pathToDockerFile
        default: /workspace/extracted/Dockerfile
      - name: pathToContext
        default: /workspace/extracted
  outputs:
    resources:
      - name: docker-image
        type: image
  steps:
    - name: build-push-step
      env:
      - name: DOCKER_CONFIG
        value: /tekton/home/.docker
      image: gcr.io/kaniko-project/executor:v0.15.0
      command: [ "/kaniko/executor" ]
      args:
        - --dockerfile=$(inputs.params.pathToDockerFile)
        - --destination=$(outputs.resources.docker-image.url)
        - --context=$(inputs.params.pathToContext)
        - --skip-tls-verify
