apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: create-volume-task
spec:
  inputs:
    params:
      - name: target-namespace
        default: default
  steps:
    - name: create
      image: kalantar/yq-kubernetes
      command: [ "/bin/bash" ]
      args:
        - '-c'
        - |
          NAMESPACE=$(inputs.params.target-namespace)
          kubectl --namespace ${NAMESPACE} apply --filename - <<EOF
          kind: PersistentVolumeClaim
          apiVersion: v1
          metadata:
            name: experiment-stop-claim-${NAMESPACE}
          spec:
            storageClassName: default
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 2Ki
          EOF
