apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: deploy-bookinfo-taskrun
spec:
  taskRef:
    name: deploy-bookinfo-task
  inputs:
    params:
      - name: target-namespace
        value: bookinfo-test
    resources:
      - name: git-source
        resourceRef:
          name: reviews-repo
