apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-bookinfo-task
spec:
  description: |
    Deploy the bookinfo application from the iter8 tutorials (https://iter8.tools)
    Allows changing the target namespace and the host.
  params:
  - name: NAMESPACE
    default: default
    type: string
    description: The namespace into which the application should be deployed.
  - name: HOST
    default: bookinfo.example.com
    type: string
    description: |
      The host name associated with the application. 
      Configured in the gateway and virtualservice;
      Should be included in requests in a Host header.
  steps:
  - name: deploy-bookinfo
    image: kalantar/yq-kubernetes
    script: |
      #!/usr/bin/env bash
      set -x

      # Copy params into shell variables
      NAMESPACE=$(params.NAMESPACE)
      HOST=$(params.HOST)
      echo "NAMESPACE = ${NAMESPACE}"
      echo "     HOST = ${HOST}"

      # Create namespace
      curl -s https://iter8.tools/tutorials/namespace.yaml \
        | sed "s#name:.*\$#name: ${NAMESPACE}#" \
        | kubectl apply --filename -

      # Create services and deployments
      kubectl --namespace ${NAMESPACE} apply --filename https://iter8.tools/tutorials/bookinfo-tutorial.yaml

      # Create virtual service and gateway
      curl -s https://iter8.tools/tutorials/bookinfo-gateway.yaml \
        | sed "s#bookinfo.example.com#${HOST}#" \
        | kubectl apply --namespace ${NAMESPACE} --filename -
