apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: canary-rollout
spec:
  pipelineRef:
    name: canary-rollout-iter8
  serviceAccountName: default
  workspaces:
  - name: source
    persistentVolumeClaim:
      claimName: source-storage
  - name: experiment-dir
    persistentVolumeClaim:
      claimName: experiment-storage
  params:
  - name: application-source
    value: https://github.com/kalantar/reviews
  - name: application-namespace
    value: bookinfo-pipeline
  - name: application-image
    value: kalantar/reviews
  - name: application-query
    value: productpage

  - name: HOST
    value: "istio-ingressgateway-istio-system.kalantar-rh1-76c942296186c1e5a6724002dc1a424f-0000.us-south.containers.appdomain.cloud"

  - name: experiment-template
    value: iter8/experiment.yaml
